PIN_ROOT ?= /home/orestis/Downloads/pin-3.6-97554-g31f0a167d-gcc-linux

CONFIG_ROOT := $(PIN_ROOT)/source/tools/Config
include $(CONFIG_ROOT)/makefile.config
include makefile.rules
include $(TOOLS_ROOT)/Config/makefile.default.rules
